name: Build VCamera APK

on:
  workflow_dispatch:   # lets you trigger it manually
  push:
    branches: [ main ] # also runs on every push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: vcamera-apks
          path: "**/build/outputs/apk/**/*.apk"
