name: Build VCamera APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ✅ Install cmdline-tools + ALL required packages AND accept licenses in one shot
      - name: Install Android SDK + packages (licenses pre-accepted)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            cmdline-tools;latest
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Use hosted Gradle (repo has no ./gradlew)
      - name: Setup Gradle (no cache)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10
          cache-disabled: true

      - name: Build debug APK (verbose)
        run: gradle assembleDebug --stacktrace --info

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: vcamera-apks
          path: "**/build/outputs/apk/**/*.apk"
